{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pengxr.android",
    "module": "modular-eventbus-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.pengxr.android",
          "module": "modular-eventbus-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "modular-eventbus-processor-1.0.0.jar",
          "url": "modular-eventbus-processor-1.0.0.jar",
          "size": 27176,
          "sha512": "5b9bcf61487b3d620df7fcca4490759c7130f755f3bb5b98aa9e9bf80959ee0e818d3402b21565dd89274258a96f24eaeabb1606388426f890a2f149be9d6890",
          "sha256": "ef0f81f3930486042006b2eb0ed3ac0d6365675f289f4b78a4c80945ccf1306b",
          "sha1": "27e2e7767560c48322961a6fde3dbb4d20ece423",
          "md5": "c6d7548b027aaec01a02e74db08d5634"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc7"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.48"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.pengxr.android",
          "module": "modular-eventbus-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "modular-eventbus-processor-1.0.0.jar",
          "url": "modular-eventbus-processor-1.0.0.jar",
          "size": 27176,
          "sha512": "5b9bcf61487b3d620df7fcca4490759c7130f755f3bb5b98aa9e9bf80959ee0e818d3402b21565dd89274258a96f24eaeabb1606388426f890a2f149be9d6890",
          "sha256": "ef0f81f3930486042006b2eb0ed3ac0d6365675f289f4b78a4c80945ccf1306b",
          "sha1": "27e2e7767560c48322961a6fde3dbb4d20ece423",
          "md5": "c6d7548b027aaec01a02e74db08d5634"
        }
      ]
    }
  ]
}
