{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pengxr.android",
    "module": "modular-eventbus-annotation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "modular-eventbus-annotation-1.0.0.jar",
          "url": "modular-eventbus-annotation-1.0.0.jar",
          "size": 3219,
          "sha512": "e8fc298c0837994db820a036b19aac19d81990af3f4dd4bb51c37e9bd44ce836271b1f161a221a57f8409338444cd4bd347ebba0a35080f66742b2dcabbdf75d",
          "sha256": "c73b6701a113c1479f34913c32f7f4e4b56a02f4bc32336d0a81ddd62d87d5f0",
          "sha1": "767df77fd3e56eb05160fd53415775a6b61b7743",
          "md5": "97895e61b032cafce77acbc9c5ff5c19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "modular-eventbus-annotation-1.0.0.jar",
          "url": "modular-eventbus-annotation-1.0.0.jar",
          "size": 3219,
          "sha512": "e8fc298c0837994db820a036b19aac19d81990af3f4dd4bb51c37e9bd44ce836271b1f161a221a57f8409338444cd4bd347ebba0a35080f66742b2dcabbdf75d",
          "sha256": "c73b6701a113c1479f34913c32f7f4e4b56a02f4bc32336d0a81ddd62d87d5f0",
          "sha1": "767df77fd3e56eb05160fd53415775a6b61b7743",
          "md5": "97895e61b032cafce77acbc9c5ff5c19"
        }
      ]
    }
  ]
}
